version: "3.8"

networks:
  todo_net:
    driver: overlay
    
secrets:
  shepherd-registries-auth:
    external: true
    
services:
  todo_list:
    image: 52.221.188.143:5000/todo-app:latest
    deploy:
      labels: 
        - shepherd.enable=true
        - shepherd.auth.config=todo
    ports:
      - "5173:5173"
    networks: 
      - todo_net

  shepherd:
    image: containrrr/shepherd:latest
    volumes:
      - type: bind
        source: ./certs
        target: /etc/docker/certs.d/52.221.188.143:5000
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true   
    secrets:
      - shepherd-registries-auth
    environment:
      - SLEEP_TIME=1m
      - IGNORELIST_SERVICES=shepherd
      - IMAGE_AUTOCLEAN_LIMIT=5
      - ROLLBACK_ON_FAILURE=true
      - UPDATE_OPTIONS=--update-delay=30s --force
      - REGISTRIES_FILE=/var/run/secrets/shepherd-registries-auth
      - ROLLBACK_OPTIONS='--rollback-delay=0s'
      - FILTER_SERVICES=label=shepherd.enable=true
      - DOCKER_CERT_PATH=/etc/docker/certs.d/52.221.188.143:5000
      - DOCKER_TLS_CERTDIR=/etc/docker/certs.d/52.221.188.143:5000
      - DOCKER_REGISTRY_INSECURE=1
      - WITH_REGISTRY_AUTH=true
      - TZ=Asia/Manila
      - VERBOSE=true
      
      
    networks: 
      - todo_net
    deploy:
      placement:
        constraints:
          - node.hostname == tns-ubu106