version: "3.8"

networks:
  todo_net:
    driver: overlay
    
secrets:
  shepherd-registries-auth:
    external: true

configs:
  config_json:
    file: ./config.json
#   daemon_json:
#     file: ./daemon.json

services:
  todo_list:
    image: spark.fb2fn.com/todo-app
    deploy:
      labels: 
        - shepherd.enable=true
        - shepherd.auth.config=todo
    ports:
      - "5173:5173"
    networks: 
      - todo_net

  shepherd:
    image: containrrr/shepherd:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    configs:
      - source: config_json
        target: /root/.docker/config.json
    #   # - source: daemon_json
    #   #   target: /etc/docker/daemon.json
    secrets:
      - shepherd-registries-auth

    environment:
      - SLEEP_TIME=1m
      - IGNORELIST_SERVICES=shepherd
      - IMAGE_AUTOCLEAN_LIMIT=5
      - ROLLBACK_ON_FAILURE=true
      - UPDATE_OPTIONS=--update-delay=30s --force --with-registry-auth
      - ROLLBACK_OPTIONS='--rollback-delay=0s'
      - FILTER_SERVICES=label=shepherd.enable=true
      - TZ=Asia/Manila
      - VERBOSE=true
      - REGISTRY_HOST=https://spark.fb2fn.com
      - WITH_REGISTRY_AUTH=true
      - REGISTRIES_FILE=/var/run/secrets/shepherd-registries-auth

    deploy:
      placement:
        constraints:
          - node.role == manager
