version: '3.8'
services:
  registry:
    image: registry:2.8.1
    ports:
      - 5000:5000
    deploy:
      placement:
        constraints:
          - node.hostname == tns-ubu106
    networks:
      - registry-net

networks:
  registry-net:
    driver: overlay
