version: "3.8"    
services:
  todo_list:
    image: 52.221.188.143:5001/todo-app:latest
    deploy:
      labels: 
        - shepherd.enable=true
        - shepherd.auth.config=todo
    ports:
      - "5173:5173"
    deploy:
      placement:
        constraints:
          - node.hostname == tns-ubu106