version: "3.8"

networks:
  todo_net:
    driver: overlay
  registry_registry-net:
    external: true

services:
  todo_list:
    image: 172.24.31.39:5000/alhon05/todo-app:latest
    deploy:
      labels: 
        - shepherd.enable=true

    ports:
      - "5173:5173"
    networks: 
      - todo_net
      - registry_registry-net

  shepherd:
    image: containrrr/shepherd:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - SLEEP_TIME=1m
      - IGNORELIST_SERVICES=shepherd
      - IMAGE_AUTOCLEAN_LIMIT=5
      - ROLLBACK_ON_FAILURE=true
      - UPDATE_OPTIONS=--update-delay=30s --force
      - ROLLBACK_OPTIONS='--rollback-delay=0s'
      - VERBOSE=true
      - FILTER_SERVICES=label=shepherd.enable=true
      - TZ=Asia/Manila
      - WITH_INSECURE_REGISTRY=true

    networks: 
      - todo_net
      - registry_registry-net

    deploy:
      placement:
        constraints:
          - node.role == manager
