version: "3.8"

networks:
  watchtower_net:
    driver: overlay

secrets:
  shepherd-registries-auth:
    external: true

services:
  todo_list:
    image: alhon05/todo-app:latest
    deploy:
      labels: 
        - com.mydomain.autodeploy
        - shepherd.auth.config=todo
        - shepherd.enable=true

    ports:
      - "5173:5173"
    networks: 
      - watchtower_net

  shepherd:
    build: .
    image: containrrr/shepherd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - SLEEP_TIME=1m
      - IGNORELIST_SERVICES=shepherd
      - IMAGE_AUTOCLEAN_LIMIT=5
      - ROLLBACK_ON_FAILURE=true
      - WITH_REGISTRY_AUTH=true
      - UPDATE_OPTIONS=--update-delay=30s --force
      - ROLLBACK_OPTIONS='--rollback-delay=0s'
      - VERBOSE=true
      - FILTER_SERVICES=label=com.mydomain.autodeploy
      - TZ=Asia/Manila

    # entrypoint: ["/bin/sh", "-c", "/entrypoint.sh shepherd"]
    secrets:
      - shepherd-registries-auth

    deploy:
      placement:
        constraints:
          - node.role == manager
    networks: 
      - watchtower_net