version: "3.8"

networks:
  todo_net:
    driver: overlay
secrets:
  shepherd-registries-auth:
    external: true
  registry_username:
    external: true
  registry_password:
    external: true

services:
  todo_list:
    image: spark.fb2fn.com/todo-app:latest
    deploy:
      labels: 
        - shepherd.enable=true
        - shepherd.auth.config=todo
    ports:
      - "5173:5173"
    networks: 
      - todo_net

  shepherd:
    image: containrrr/shepherd:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - SLEEP_TIME=1m
      - IGNORELIST_SERVICES=shepherd
      - IMAGE_AUTOCLEAN_LIMIT=5
      - ROLLBACK_ON_FAILURE=true
      - UPDATE_OPTIONS=--update-delay=30s --force --with-registry-auth
      - ROLLBACK_OPTIONS='--rollback-delay=0s'
      - FILTER_SERVICES=label=shepherd.enable=true
      - TZ=Asia/Manila
      - VERBOSE=true
      - REGISTRY_HOST=spark.fb2fn.com
      - WITH_REGISTRY_AUTH=true
      - REGISTRIES_FILE=/var/run/secrets/shepherd-registries-auth

    secrets:
      - shepherd-registries-auth

    deploy:
      placement:
        constraints:
          - node.role == manager
