version: "3.8"

networks:
  todonet:
    driver: overlay

services:
  todo_list:
    image: alhon05/todo-app:latest
    ports:
      - "5173:5173"
    deploy:
      labels:
        - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - TZ=UTC
    networks: 
      - todonet

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:1.7.1
    deploy:
      mode: global
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --debug --label-enable
    networks: 
      - todonet
