version: "3.8"

networks:
  watcher_watchtower_net:
    external: true

services:
  todo_list:
    image: alhon05/todo-app:latest
    ports:
      - "5173:5173"
    deploy:
      labels:
        - "com.centurylinklabs.watchtower.enable=true"
    networks: 
      - watcher_watchtower_net
