name: pipeline
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  deploy:
    name: build && push image to local registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'dev'
      - name: Login to fb2fn repo
        uses: docker/login-action@v2
        with:
          registry: spark.fb2fn.com
          username: ${{ secrets.REPO_USERNAME }}
          password: ${{ secrets.REPO_PASSWORD }}
          logout: true
    


