name: pipeline
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  deploy:
    name: build && push image to local registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'dev'
    
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract Git Commit SHA
        id: vars
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      - name: build and push api
        id: build-push-api
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            172.24.31.39:5000/alhon05/todo-app:lastest
            172.24.31.39:5000/alhon05/todo-app:${{ github.ref_name }}-${{ env.GIT_SHA }}

      - name: Verify image in local registry
        run: curl http://172.24.31.39:5000/v2/_catalog
